#+TITLE: Simulation numérique par éléments finis avancés / Méthodes numériques pour les écoulements incompressibles
#+AUTHOR: Yves Coudière
#+DATE: [2018-10-08 lun.]
#+EMAIL: yves.coudiere at u-bordeaux.fr [05 24 57 40 36]
#+LANGUAGE: fr

* Proposition nouveau syllabus
cf les emails de discusssion: [[mu4e:msgid:c659e82d-ad41-9455-08da-053a16405886@math.u-bordeaux.fr][amélioration de la filière CHP]], [[mu4e:msgid:8A866553-25EB-460B-B4EB-D02B82AE50EF@math.u-bordeaux.fr][Re: amélioration
de la filière CHP]] et [[mu4e:msgid:8960b83e-1840-5970-9adb-f4ad373c5d1f@enseirb-matmeca.fr][Re: amélioration de la filière CHP]]
** Compétences
 - Savoir construire une formulation variationnelle pour un problème de
   mécanique des milieus continus, les fluides (Stokes) ou les solides
   déformables (élasticité).
 - Connaitre quelques éléments finis classiques en dimension 2 et 3 (Lagrange
   Pk, isoparamétriques Qk, élément bulles pour Stokes...) et leurs propriétés
   d'approximation, savoir choisir l'élément en fonction de l'application.
 - Comprendre l'implémentation d'un code éléments finis sur maillage non
   structuré.
** Contenu du cours
 1. Formulations variationnelles en mécanique des milieus continus,
   - équations de Stokes
   - élasticité linéaire
 2. Méthode des éléments finis
   - rappels sur le principe de la méthode (méthode de Galerkin, définition d'un
     élément unisolvant)
   - maillages non structurés et construction des espaces d'approximation
   - principe général de la construction de systèmes linéaires
 3. Mise en oeuvre
   - représentation des maillages
   - principe des procédures d'assemblage des matrices
   - calcul des matrices élémentaires par passage à l'élément de référence
** Organisation pratique
- Première partie :: cours "magistraux" permettant de rappeler
     brièvement les 3 points ci-dessus.
- Deuxième partie :: réalisation d'un projet qui sera dédié, soit à la
     programmation complète d'un solveur, soit à l'utilisation de
     Freefem++ pour la résolution et l'exploration d'un problème
     complexe, soit à une étude théorique d'analyse numérique.
* Organisation pratique, évaluation
** Codes
 - Matmeca : EM9AN312
 - UB : ??
** Temps de travail (accréditation)
 - 24h CM -> 36 h eqTD  
** Évaluation
 - Session 1 : Contrôle continu - Coef. 1 (évaluation sur projets)
 - Session 2 : Pas de 2e session

Les épreuves terminales écrites pourront être remplacées en seconde
session par un oral en cas d'effectif faible
** EdT
https://ade.bordeaux-inp.fr/direct/index.jsp?displayConfName=web&login=visu&projectId=2

** Travail
- TP1 à faire individuellement (séance du 30/10), compte rendu à
  remettre avant la fin de la semaine
  (yves.coudiere@u-bordeaux.fr). Voir le répertoire [[file:./freefem][./freefem]], l'énoncé
  se trouve dans le fichier [[file:./freefem/tp.pdf][./freefem/tp.pdf]].
- Projets à répartir par groupes [[file:./projets.pdf][projets.pdf]].
- Chaque projet fait l'objet 
    + d'un ensemble d'exposés à donner au cours du semestre 
    + d'un compte rendu global qui regroupe les éléments des exposés et
      les éléments complémentaires éventuels, à rendre en fin de semestre.


